version: "2"
engines:
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
      - test
      - lib/parsers/FeatureParser.js
      - lib/localisation/*
checks:
  method-complexity:
    enabled: false
  method-lines:
    enabled: false

ratings:
  paths:
  - index.js
  - lib/**

exclude_paths:
  - bin
  - dist
  - examples
